name: First CI tests

on:
  push:
    branches:
      - pytest


jobs:
  
  job1:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v4 is the version of the action we're using, not the branch of the code; https://github.com/actions/checkout 
        # purpose of checkout code is to get the code from the repository, and put it in the runner machine

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          ls -R  # Debugging step to list all files
          pip install -r flask_CD_pipelines/requirements.txt


      - name: Run tests
        run: |
          pytest


  job2:
    needs: job1
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  

      - name: Build Docker Image and push to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/flask_CD_pipelines
          push: true
          tags: |
            biplabinipadhi/first-action:latest
            biplabinipadhi/first-action:${{ github.sha }}
