name: First CI tests

on:
  push:
    branches:
      - main

jobs:
  
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r flask_CD_pipelines/requirements.txt  # Ensure correct path

      - name: Run tests
        run: pytest


  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use Personal Access Token

      - name: Build Docker Image and push to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/flask_CD_pipelines
          push: true
          tags: |
            biplabinipadhi/first-action:latest
            biplabinipadhi/first-action:${{ github.sha }}
